## Learning Objectives

- How we can exctract keywords from corpus (collections of texts) using TF-IDF

- Explain what is TF-IDF

- Applications of keywords exctraction algorithm and Word2Vec

## Review: What are the pre-processings to apply a machine learning algorithm on text data?

1. The text must be parsed to words, called tokenization

2. Then the words need to be encoded as integers or floating point values

3. scikit-learn library offers easy-to-use tools to perform both tokenization and feature extraction of text data

## What is TF-IDF Vectorizer?

- Word counts are a good starting point, but are very basic

An alternative is to calculate word frequencies, and by far the most popular method is called TF-IDF. 

**Term Frequency**: This summarizes how often a given word appears within a document

**Inverse Document Frequency**: This downscales words that appear a lot across documents

## Intuitive idea behind TF-IDF:
    
- If a word appears frequently in a document, it's important. Give the word a high score

- But if a word appears in many documents, it's not a unique identifier. Give the word a low score

<img src="Images/tfidf_slide.png" width="700" height="700">

## Activity: Obtain the keywords from TF-IDF

1- First obtain the TF-IDF matrix for given corpus

2- Do column-wise addition

3- Sort the score from highest to lowest

4- Return the associated words based on step 3

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import numpy as np

def keyword_sklearn(docs, k):
    vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = vectorizer.fit_transform(docs)
    print(tfidf_matrix.toarray())
    print(vectorizer.get_feature_names())
    tfidf_scores = np.sum(tfidf_matrix, axis=0)
    tfidf_scores = np.ravel(tfidf_scores)
    return sorted(dict(zip(vectorizer.get_feature_names(), tfidf_scores)).items(), key=lambda x: x[1], reverse=True)[:k]

documnets = ['The sky is bule', 'The sun is bright', 'The sun in the sky is bright', 'we can see the shining sun, the bright sun']

# print(keyword_sklearn(documnets, 3))












from sklearn.feature_extraction.text import TfidfVectorizer
docs = ['The sky is bule', 'The sun is bright', 'The sun in the sky is bright', 'we can see the shining sun, the bright sun']
vectorizer = TfidfVectorizer(stop_words='english')
mat = vectorizer.fit_transform(docs)
matrix = mat.toarray()
print(matrix)
# print(vectorizer.get_feature_names())  # which types of words do we have, after dropping stop words


'''# column wise addition
scores1 = sum(matrix[:, 0])
print(scores1)
scores2 = sum(matrix[:, 1])
print(scores2)
scores3 = sum(matrix[:, 2])
print(scores3)
scores4 = sum(matrix[:, 3])
print(scores4)
scores = sorted([scores1, scores2, scores3, scores4])
print(scores)
'''

# column wise addition
features = vectorizer.get_feature_names()
scores = {}
for i in range(len(matrix)):
    # print(matrix[:, i])
    scores[features[i]] = sum(matrix[:, i])
print(sorted(scores.items()))





[[0.         0.78528828 0.         0.6191303  0.        ]
 [0.70710678 0.         0.         0.         0.70710678]
 [0.53256952 0.         0.         0.65782931 0.53256952]
 [0.36626037 0.         0.57381765 0.         0.73252075]]
[('bright', 1.605936677684143), ('bule', 0.7852882757103967), ('shining', 0.5738176501168697), ('sky', 1.27695960978985)]


## Word2Vec

- Data Scientists have assigned a vector to each english word

- This process of assignning vectors to each word is called Word2Vec

- In DS 2.4, we will learn how they accomplished Word2Vec task

- Download this huge Word2Vec file: https://nlp.stanford.edu/projects/glove/

- Do not open the extracted file

## What is the property of vectors associated to each word in Word2Vec?

- Words with similar meanings would be closer to each other in Euclidean Space

- For example if $V_{pizza}$, $V_{food}$ and $V_{sport}$ represent the vector associated to pizza, food and sport then:

${\| V_{pizza} - V_{food}}\|$ < ${\| V_{pizza} - V_{sport}}\|$

## Acitivity: Obtain the vector associated to pizza in Glove

In [37]:
import codecs

with codecs.open('Datasets/glove.6B/glove.6B.300d.txt', 'r') as f:
    for c, r in enumerate(f):
        sr = r.split()
        if sr[0] == 'pizza':
            print(sr[0])
            print([float(i) for i in sr[1:]])
            print(len([float(i) for i in sr[1:]]))
            break

pizza
[0.25734, 0.4834, 0.39895, -0.021904, -0.23251, 0.1912, -0.060446, -0.25761, -0.45211, 0.041514, -0.2691, -0.70659, -0.19061, 0.61703, -0.31782, 0.027941, -0.16662, -0.10881, -0.34464, 0.42024, 0.36226, 0.72459, -0.037924, -0.13019, 0.41046, -0.053523, 0.24423, 0.018026, 0.43282, -1.2634, -0.54086, 0.47269, 0.35893, -0.26779, -0.57371, 0.35586, -0.3969, -0.35332, -0.48882, 0.24765, 0.15628, 0.03886, 0.0079223, 0.54105, -0.13862, 0.32459, 1.0425, 0.12856, 0.036834, -0.22976, -0.087973, -0.69039, 0.35075, 0.56834, -0.19602, -0.2434, -0.075702, 0.37302, 0.14015, -0.24343, 0.79112, -0.25912, -0.017421, -0.46356, -0.12607, -0.37098, -0.23651, 0.50475, -0.30574, 0.28055, 0.52918, 0.15871, -0.098648, -0.40663, 0.13522, -0.23016, -0.15465, -0.10037, -0.06647, -0.35895, -0.12413, 0.44327, 0.082424, -0.44134, -0.14447, -0.48395, 0.29215, 0.24427, -0.32845, 0.054433, 0.2512, 0.13315, -0.16265, -0.12271, -0.0041962, 0.048386, -0.28681, 0.20425, -0.40364, 0.097275, 0.33175, -0.087691, 0.01002

## Activity: Obtain the vectors associated to pizza, food and sport in Glove

In [44]:
import codecs
import numpy as np

with codecs.open('Datasets/glove.6B/glove.6B.300d.txt', 'r') as f:
    ls = {}
    for c, r in enumerate(f):
        sr = r.split()
        if sr[0] in ['pizza', 'food', 'sport']:
            ls[sr[0]] =[float(i) for i in sr[1:]]
        if len(ls) == 3:
            break

print(ls)
''' # words = ['pizza', 'food', 'sport']
    words_vecs = {}
    for c, r in enumerate(f):
        sr = r.split()
        if sr[0] == 'pizza':
           words_vecs['pizza'] = [float(i) for i in sr[1:]]
        elif sr[0] == 'food':
           words_vecs['food'] = [float(i) for i in sr[1:]]
        elif sr[0] == 'sport':
           words_vecs['sport'] = [float(i) for i in sr[1:]]
        
    print(words_vecs)
    # verify that the pizza and food are closer together than pizza and sport, using Euclidean distance
    distance_p_f = np.linalg.norm( words_vecs['pizza'], words_vecs['food'])
    print(distance_p_f)'''

{'food': [0.38544, 0.34247, 0.29599, -0.262, 0.037383, 0.45544, 0.49097, 0.11481, -0.11437, -1.9067, 0.035563, -1.1094, -0.26512, 0.64418, -0.031008, -0.3513, -0.0010547, 0.074658, -0.30369, -0.28188, -0.34342, 0.36205, 0.71009, 0.30243, 0.070325, 0.29492, -0.16233, 0.30998, 0.13705, 0.11847, -0.68642, 0.43305, -0.61518, 0.23643, -0.84174, 0.14667, -0.096616, -0.20908, -0.42296, -0.27254, -0.79343, -0.62781, 0.64804, 0.11541, -0.33486, -0.14101, 0.12864, -0.25123, -0.26515, 0.30876, -0.063111, 0.17893, 0.41197, 0.019621, -0.15406, 0.17542, 0.39268, 0.088817, 0.018012, -0.22508, -0.31832, 0.022296, 0.59453, 0.056538, -0.72464, -0.31751, -0.3865, 0.33806, -0.16237, -0.0076169, 0.52897, 0.14628, -0.22458, -0.66751, 0.23012, -0.068667, 0.4668, 0.2204, -0.38321, -0.18401, 0.36828, 0.085637, -0.28836, 0.43894, 0.1579, -1.1443, -0.17327, -0.0027353, -0.32621, -0.2411, -0.14597, 0.061719, -0.3021, -0.16319, 0.0025848, 0.26203, 0.045155, -0.019056, -0.48923, 0.062269, 0.1214, 0.054817, 0.01157,

" # words = ['pizza', 'food', 'sport']\n    words_vecs = {}\n    for c, r in enumerate(f):\n        sr = r.split()\n        if sr[0] == 'pizza':\n           words_vecs['pizza'] = [float(i) for i in sr[1:]]\n        elif sr[0] == 'food':\n           words_vecs['food'] = [float(i) for i in sr[1:]]\n        elif sr[0] == 'sport':\n           words_vecs['sport'] = [float(i) for i in sr[1:]]\n        \n    print(words_vecs)\n    # verify that the pizza and food are closer together than pizza and sport, using Euclidean distance\n    distance_p_f = np.linalg.norm( words_vecs['pizza'], words_vecs['food'])\n    print(distance_p_f)"

## Acitivty: Show that the vector of pizza is closer to vector of food than vector of sport

In [45]:
import numpy as np

np.linalg.norm(np.array(ls['pizza']) - np.array(ls['food']))

7.63426225303502

In [46]:
np.linalg.norm(np.array(ls['pizza']) - np.array(ls['sport']))

9.341560240989656

In [47]:
np.linalg.norm(np.array(ls['food']) - np.array(ls['sport']))

8.896379012366626

In [52]:
# sort a dictionary by its values
x = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
y = {k: v for k, v in sorted(x.items(), key=lambda item: item[1])}
#{0: 0, 2: 1, 1: 2, 4: 3, 3: 4}
z = [sorted([value, key]) for key, value in x.items()]
z

[[1, 2], [3, 4], [3, 4], [1, 2], [0, 0]]